Regen configure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -662,6 +662,7 @@ INSTALL_DATA
 CPP
 GREP
 EGREP
+CC_MKDEP_FLAGS
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -4923,6 +4924,62 @@ _ACEOF
     fi
 fi
 
+{ echo "$as_me:$LINENO: checking for C compiler option to generate Makefile dependencies" >&5
+echo $ECHO_N "checking for C compiler option to generate Makefile dependencies... $ECHO_C" >&6; }
+if test "${my_cc_cv_mkdep_flags+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  my_cc_cv_mkdep_flags=-M
+                cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+#ifndef __SUNPRO_C
+       not sunpro
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  my_cc_cv_mkdep_flags=-xM
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $my_cc_cv_mkdep_flags" >&5
+echo "${ECHO_T}$my_cc_cv_mkdep_flags" >&6; }
+CC_MKDEP_FLAGS=$my_cc_cv_mkdep_flags
+
+
 if test xyes = x"$GCC" && test xyes != x"$had_prior_cflags"
 then
     CFLAGS="$CFLAGS -Wall -Werror"
@@ -5595,11 +5652,12 @@ INSTALL_DATA!$INSTALL_DATA$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
+CC_MKDEP_FLAGS!$CC_MKDEP_FLAGS$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 52; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 53; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
